### ISSUE TITLE
PLEASE FOR THE LOVE OF §

### ISSUE THREAD

**Issue by SirGamers** [CdrJohannsen/Allow-Chat#2]
UPDATE THIS TO 1.21
[if you don't, then...](https://www.youtube.com/watch?v=L_WoOkDAqbM)

**Comment by CdrJohannsen** [comment]
https://www.google.com/search?q=how+to+write+a+good+github+issue

Here you go: https://modrinth.com/mod/allow-chat/version/1.1.0
